security:
    providers:
        hwi:
            #id: hwi_oauth.user.provider
            id: App\Security\UserProvider

    firewalls:
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    auth0: "/auth0/callback"
                login_path:        /connect/auth0
                default_target_path: dashboard
                use_forward:       false
                failure_path:      /connect/auth0

                oauth_user_provider:
                    #service: hwi_oauth.user.provider
                    service: App\Security\UserProvider
            logout:
                path:   /auth0/logout
                target: homepage
        main:
            anonymous: ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/homepage, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/calendar, roles: ROLE_OAUTH_USER }
        - { path: ^/data, roles: ROLE_OAUTH_USER }
        - { path: ^/dashboard, roles: ROLE_OAUTH_USER }
        - { path: ^/dsm5-disorder, roles: ROLE_OAUTH_USER }
        - { path: ^/measure, roles: ROLE_OAUTH_USER }
        - { path: ^/observation, roles: ROLE_OAUTH_USER }
        - { path: ^/observation-phase, roles: ROLE_OAUTH_USER }
        - { path: ^/student, roles: ROLE_OAUTH_USER }
        - { path: ^/student-health-information, roles: ROLE_OAUTH_USER }
        - { path: ^/secured, roles: ROLE_OAUTH_USER }
        - { path: ^/user, roles: ROLE_OAUTH_USER }
